# Generated by Django 4.2.2 on 2023-06-07 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='statu',
            field=models.CharField(choices=[('DOING', 'DOING'), ('DONE', 'DONE'), ('TODO', 'TODO')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemlist',
            name='type',
            field=models.CharField(choices=[('P', 'Pessoal'), ('A', 'Para todos')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('AD', 'Admin'), ('PR', 'Professor'), ('AL', 'Aluno')], max_length=2)),
                ('item_list', models.ManyToManyField(blank=True, to='client.itemlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
