# Generated by Django 4.2.2 on 2023-06-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_itemlist_statu_itemlist_type_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='statu',
            new_name='status',
        ),
    ]
