# Generated by Django 4.2.2 on 2023-06-07 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_statu_itemlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.discipline'),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.teacher'),
        ),
    ]
