# Generated by Django 4.2.2 on 2023-06-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_itemlist_discipline_alter_itemlist_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='status',
            field=models.CharField(choices=[('DOING', 'Doing'), ('DONE', 'Done'), ('TODO', 'To Do')], max_length=5),
        ),
    ]
