# Generated by Django 4.2.2 on 2023-07-11 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_itemlist_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='is_technical_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
