# Generated by Django 4.2.2 on 2023-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_discipline_is_technical_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
