# Generated by Django 4.2.2 on 2023-07-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_itemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='due_date',
            field=models.DateField(),
        ),
    ]
