# Generated by Django 4.2.1 on 2023-05-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemlist",
            name="due_date",
            field=models.DateField(),
        ),
    ]
